#!/usr/bin/env sh

# This script is meant to be used from the Arch Linux liveiso.
# It will walk you through the installation process for Arch Linux.

### HELPERS ###

end() {
  printf '%s\n' "$1" >&2 && exit 1 # log to stderr and exit with failure
}

install() {
  pacman --noconfirm --needed -S "$1" >/dev/null 2>&1
}

welcome() {
  gum confirm --prompt.foreground 99 --prompt.border-foreground 105 --prompt.width 55 \
    --prompt.margin "1 2" --prompt.padding "1 2" --prompt.border double \
    --prompt.align center --affirmative "Continue" --negative "End" \
    --default "Welcome to irisfield's Arch Linux RICE installer.
This script installs a minimal Linux desktop using irisfield's dotfiles."
}

get_username() {
  username=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Account name: " \
    --placeholder "(enter a name for the user account)")
  while ! echo "$username" | grep -q "^[a-z_][a-z0-9_-]*$"; do
    username=$(gum input --prompt.foreground 99 --prompt.bold \
      --prompt "Try again. Account name: " \
      --placeholder "(only lowercase letters, - and _ are allowed)")
  done
}

get_password() {
  password=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Password: " \
    --password --placeholder "(enter a password for the root user)")
  verify=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Verify: " \
    --password --placeholder "(retype the password)")
  while ! [ "$password" = "$verify" ]; do
    unset verify
    password=$(gum input --prompt.foreground 99 --prompt.bold \
      --prompt "Try again. Password: " --password \
      --placeholder "(enter a password for the root user)")
    verify=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Verify: " \
      --password --placeholder "(retype the password)")
  done
}

get_hostname() {
  hostname=$(gum input --prompt.foreground 99 --prompt.bold --prompt "Hostname: " \
    --placeholder "(enter a name for the host)")
  while ! echo "$hostname" | grep -q "^[a-z_][a-z0-9_-]*$"; do
    hostname=$(gum input --prompt.foreground 99 --prompt.bold \
      --prompt "Try again. Hostname: " \
      --placeholder "(only lowercase letters, - and _ are allowed)")
  done
}

set_keymap() {
  keymap=""
  while [ -z "$keymap" ]; do
    # choose a keymap
    keymap=$(localectl list-keymaps --no-pager | gum filter --prompt.foreground 93 \
      --prompt.bold --prompt "Keymap: " --placeholder "(search for your keyboard layout)")
  done
  # load the selected keymap
  loadkeys "$keymap"
}

get_timezone() {
  timezone=""
  while [ -z "$timezone" ]; do
    # choose a timezone
    timezone=$(timedatectl list-timezones --no-pager | gum filter --prompt.foreground 93 \
      --prompt.bold --prompt "Timezone: " --placeholder "(search for your timezone)")
  done
  # synchronize the network time protocol
  timedatectl set-ntp true
  # display status
  timedatectl status
}

disk_partition() {
  diskname=""
  while [ -z "$diskname" ]; do
    # choose the disk to partition
    diskname=$(lsblk -Alpn -o NAME,SIZE,TYPE | grep 'disk' | gum filter \
      --prompt.foreground 93 --prompt.bold --prompt "Disk name: " \
      --placeholder "(name of disk to partition)" | cut -d' ' -f1)
  done
  # nvme drives uses the 'p' label for each partition
  label=$(echo "$diskname" | grep -q "nvme" && printf '%s' "p")
  # show the recommended layout and prompt the user
  gum confirm --prompt.foreground 99 --prompt.border-foreground 105 \
    --prompt.margin "1 2" --prompt.padding "1 2" --prompt.border thick \
    --prompt.align center --negative "Skip" \
    --default "$(gum format -t markdown "# Recommended Partition Layout
Mountpoint|Partition|ID Type|Suggested Size
-|-|-|-
/mnt/boot|${diskname}${label}1|ef EFI|512 MiB
/mnt|${diskname}${label}2|83 Linux|Remaining size")

Only an EFI and root partition are required.
You may also opt to partition the disk in any other way.
$(gum style --align center --bold --foreground 69 \
'Would you like to partition the disk?')" && unset label && cfdisk "$diskname" || return 0
}

get_efi_partition() {
  efipartition=""
  while [ -z "$efipartition" ]; do
    # choose the name of the EFI partition
    efipartition=$(lsblk -Alpn -o NAME,SIZE,TYPE | grep 'part' | gum filter \
      --prompt.foreground 93 --prompt.bold --prompt "EFI partition: " \
      --placeholder "(name of the EFI partition" | cut -d' ' -f1)
  done &&
  # confirm whether or not to format the efi partition
  gum confirm --prompt.foreground 99 --prompt.border-foreground 105 --prompt.width 55 \
    --prompt.margin "1 2" --prompt.padding "1 2" --prompt.border double \
    --prompt.align center \
    --default "$(gum style --bold --foreground 124 'EFI System Partition')
Only format the EFI partition if you created it during the partitioning step. \
Reformatting an existing EFI partition will destroy the boot loaders of other installed \
operating systems.
$(gum style --align center --bold --foreground 69 \
'Would you like to format the EFI partition?')" && formatefi="yes" || formatefi="no"
}

get_root_partition() {
  rootpartition=""
  while [ -z "$rootpartition" ]; do
    # choose the name of the root partition
    rootpartition=$(lsblk -Alpn -o NAME,SIZE,TYPE | grep 'part' | gum filter \
      --prompt.foreground 93 --prompt.bold --prompt "Root partition: " \
      --placeholder "(name of the root (/) partition)" | cut -d' ' -f1)
  done
}

suggest_swapfile() {
  # get the size of the RAM in kilobytes
  ramsize=$(grep -om 1 '[0-9]*' < /proc/meminfo)
  # get the ceiling of the RAM size in gigabytes
  ramsize=$(((ramsize + 1000000 - 1) / 1000000))
  if [ "$ramsize" -lt 16 ]; then
    gum confirm --prompt.foreground 99 --prompt.border-foreground 105 --prompt.width 55 \
      --prompt.margin "1 2" --prompt.padding "1 2" --prompt.border thick \
      --prompt.align center --default "This system has ${ramsize}GB of RAM.
A swap file double that size is recommended.
Would you like to create $((ramsize * 2))GB of swap file?" &&
      ramsize=$((ramsize * 2)) || ramsize="0"
  else
    ramsize="0"
  fi
}

input_confirmation() {
  hidden=$(for _ in $(seq 1 ${#password}); do printf '%s' "*"; done)
  gum confirm --prompt.foreground 99 --prompt.border-foreground 105 --prompt.align left \
    --prompt.margin "1 2" --prompt.padding "1 2" --prompt.border rounded \
    --default "$(gum format -t markdown "username|password|hostname|keymap|timezone
-|-|-|-|-
$username|$hidden|$hostname|$keymap|$timezone

disk|efi part|format|root part|swap
-|-|-|-|-
$diskname|$efipartition|$formatefi|$rootpartition|$ramsize GB

$(gum style --align center --bold --width 60 --foreground 69 \
  'Would you like to make changes?')")"
}

final_prompt() {
  gum confirm --prompt.foreground 99 --prompt.border-foreground 105 --prompt.width 55 \
    --prompt.margin "1 2" --prompt.padding "1 2" --prompt.border rounded \
    --prompt.align center --default "The rest of the process will now be automated.
 Would you like to proceed with the installation? "
}

create_swapfile() {
  # create swapfile and change its permission
  arch-chroot /mnt fallocate -l "${1}GiB" /maidswap &&
    arch-chroot /mnt chmod 600 /maidswap
  # make the swap and activate it
  arch-chroot /mnt mkswap /maidswap && arch-chroot /mnt swapon /maidswap
  # append the swapfile to the fstab file
  echo "/maidswap none swap defaults 0 0" >> /mnt/etc/fstab
  # print the filesystem table to stdout
  genfstab -U /mnt
}

create_user_account() {
  # create the user
  if ! arch-chroot /mnt useradd -m -g wheel -s /usr/bin/zsh "$username"; then
		arch-chroot /mnt usermod -a -G wheel "$username" &&
      arch-chroot /mnt mkdir -p /home/"$username" &&
        arch-chroot /mnt chown "$username":wheel /home/"$username"
  fi
  # set same password for the root user and the user
  arch-chroot /mnt echo "root:$password" | chpasswd
  arch-chroot /mnt echo "$username:$password" | chpasswd
  # make zsh the default shell for the user
  arch-chroot /mnt chsh -s /bin/zsh "$username" >/dev/null 2>&1
  unset password verify
}

install_aur_helper() {
  parudir="/home/$username/.cache/paru/clone"
  mkdir -p "$parudir" && chown -R "$username":wheel "${parudir%/*/*}"
  gum spin --spinner line --show-output --title "Installing paru, an AUR helper..." -- \
    doas -u "$username" git -C "$parudir" clone -q "https://aur.archlinux.org/paru.git" &&
    cd "${parudir}/paru" && doas -u "$username" makepkg --noconfirm -si
}

main_install() {
  mpk=$(printf '\n%b %b' "\033[1m$1\033[21m" "$2")
  gum spin --spinner line --title "($n/$total) Installing $1.$mpk" -- \
    pacman --noconfirm --needed -S "$1"
}

paru_install() {
  apk=$(printf '\n%b %b' "\033[1m$1\033[0m" "$2")
  gum spin --spinner line --title "($n/$total) Installing $1 from the AUR.$apk" -- \
    doas -u "$username" paru --noconfirm --needed -S "$1"
}

get_packages() {
  if [ -f "./packages.csv" ]; then
    trap 'rm -f /packages.csv' EXIT HUP INT QUIT TERM
    # extract all the valid entries from the file
    grep '^[RU],[^,]\+,[^,]\+$' packages.csv > /tmp/packages.csv
    # remove any inline '#' comments
    sed -i "s/\s*#[^\"']*$//" /tmp/packages.csv
  else
    printf '%b\n' "This directory does not have a \033[37mpackages.csv\033[0m file!"
    return 1
  fi
}

install_packages() {
  if get_packages; then
    total=$(wc -l < /tmp/packages.csv) && n=0
    while IFS=, read -r repo package description; do
      n=$((n + 1))
      echo "$description" | grep -q "^\".*\"$" &&
        description="$(echo "$description" | sed -E "s/(^\"|\"$)//g")"
      case "$repo" in
        "R") main_install "$package" "$description" && n=$((n + 1)) ;;
        "U") paru_install "$package" "$description" && n=$((n + 1)) ;;
      esac
    done < /tmp/packages.csv
  fi
}

if_user_exists() {
  if id -u "$username" >/dev/null 2>&1; then
    gum confirm --prompt.foreground 99 --prompt.border-foreground 105 --prompt.width 55 \
      --prompt.margin "1 2" --prompt.padding "1 2" --prompt.border thick \
      --prompt.align center --affirmative "Proceed" --negative "Exit" \
      --default "$(gum style --bold --foreground 124 "WARNING")
The user '$username' already exists on this system! \
Would you like to proceed with the installation and overwrite conflicting \
settings and dotfiles for this user?" &&
    gum confirm --prompt.foreground 99 --prompt.border-foreground 105 --prompt.width 55 \
      --prompt.margin "1 2" --prompt.padding "1 2" --prompt.border thick \
      --prompt.align center --negative "Exit" \
      --default "$(gum style --bold --foreground 124 "WARNING")
Settings and dotfiles aside, no other file in the home directory will be affected. \
Note that this will change the user's password to the new one.
$(gum style --width 55 --align middle --bold --foreground 69 \
  'Are you sure you would like to proceed?')"
  fi
}

### START OF THE SCRIPT ###

# just in case, make sure the distribution is Arch Linux
[ "$(lsb_release -is)" = "Arch" ] || end "this installer only works on Arch Linux"

# verify that the system is booted in UEFI mode
[ ! -d /sys/firmware/efi/efivars ] &&
  end "please boot the system in UEFI mode and try again"

# check for the root user
[ "$(id -u)" -eq 0 ] || end "please run this script from the Arch Linux liveiso"

# test for an internet connection and install gum
pacman --noconfirm --needed -Sy gum >/dev/null 2>&1 ||
  end "pacman failed, please make sure you have an internet connection"

welcome || end "bye bye"

get_username || end "exited"

get_password || end "exited"

get_hostname || end "exited"

set_keymap || end "something went wrong at set_keymap"

get_timezone || end "something went wrong at get_timezone"

disk_partition || end "exited"

get_efi_partition || end "exited"

get_root_partition || end "exited"

suggest_swapfile || end "exited"

if_user_exists || end "exited"

while input_confirmation; do
  case "$(gum choose "username" "password" "host" \
    "keymap" "timezone" "disk" "efi" "root" "swap")" in
    username)
      get_username ;;
    password)
      get_password ;;
    host)
      get_hostname ;;
    keymap)
      set_keymap ;;
    timezone)
      get_timezone ;;
    disk)
      disk_partition ;;
    efi)
      get_efi_partition ;;
    root)
      get_root_partition ;;
    swap)
      suggest_swapfile ;;
  esac
done

final_prompt || end "exited"

# refresh archlinux keyring and install reflector
pacman --needed --noconfirm -S archlinux-keyring reflector ||
  end "pacman failed, please make sure you have an internet connection"

# heading
gum style --align center --foreground 99 --width 60 --margin "1 2" --padding "1 2" \
  "Updating mirrors using reflector"

# update the mirror list using reflector to have the fastest servers
reflector --protocol https --country US --age 6 --latest 45 --fastest 15 \
  --save /etc/pacman.d/mirrorlist >/dev/null 2>&1 && pacman -Sy ||
    printf '%s\n' "reflector failed, skipping..."


# heading
gum style --align center --foreground 99 --width 60 --margin "1 2" --padding "1 2" \
  "Filesystem table (fstab) file"

# format the partitions
gum spin --spinner line --show-output --title "Formatting the partitions..." -- \
  mkfs.ext4 "$rootpartition" && [ "$formatefi" = "yes" ] && mkfs.fat -F 32 "$efipartition"

# mount the partitions
gum spin --spinner line --title "Mounting the partitions..." -- \
mount "$rootpartition" /mnt && mount --mkdir "$efipartition" /mnt/boot

# detect cpu vendor
lscpu | grep -Eiq 'id.*amd' && vendor='amd' || vendor='intel'

# install the essential packages
gum spin --spinner line --title "Installing essential packages..." -- \
  pacstrap -K /mnt linux linux-firmware linux-headers base ${vendor}-ucode \
  grub efibootmgr doas dash zsh git curl ca-certificates reflector networkmanager \
  neovim bluez bluez-utils cups

### CONFIGURE THE NEW SYSTEM ###

# heading
gum style --align center --foreground 99 --width 60 --margin "1 2" --padding "1 2" \
  "Filesystem table (fstab) file"

# generate a filesystem table (fstab) file using UUID
genfstab -U /mnt >> /mnt/etc/fstab
# print fstab to stdout
genfstab -U /mnt

# create swapfile if recommended
[ "$ramsize" -gt 0 ] && create_swapfile "$ramsize"

# set the time zone
arch-chroot /mnt ln -sf /usr/share/zoneinfo/"$timezone" /etc/localtime

# synchronize the system and hardware clock
arch-chroot /mnt hwclock --systohc

gum style --align center --foreground 99 --width 60 --margin "1 2" --padding "1 2" \
  "Locale"

# uncomment and generate the needed locales
arch-chroot /mnt sed -i "s/#en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen
arch-chroot /mnt sed -i "s/#ja_JP.UTF-8/ja_JP.UTF-8/" /etc/locale.gen
arch-chroot /mnt locale-gen

# persist the selected keymap and locales
arch-chroot /mnt echo "KEYMAP=$keymap" > /etc/vconsole.conf
arch-chroot /mnt echo "LANG=en_US.UTF-8" > /etc/locale.conf

### NETWORK CONFIGURATION ###

# create the hostname file
arch-chroot /mnt echo "$hostname" > /etc/hostname

# create the local hostname
arch-chroot /mnt tee -a /etc/hosts >/dev/null << EOT
127.0.0.1    localhost
::1          localhost
127.0.1.1    ${hostname}.localdomain $hostname
EOT

### CONFIGURATION ###

gum style --align center --foreground 99 --width 60 --margin "1 2" --padding "1 2" \
  "Create user account for root and $username"

# create the user
create_user_account

# permit the wheel group to use doas with password
arch-chroot /mnt echo "permit persist keepenv :wheel" > /etc/doas.conf

# activate services
arch-chroot /mnt systemctl enable NetworkManager
arch-chroot /mnt systemctl enable bluetooth
arch-chroot /mnt systemctl enable cups.service
arch-chroot /mnt systemctl enable reflector.timer

### BOOT LOADER ###
# heading
gum style --align center --foreground 99 --width 60 --margin "1 2" --padding "1 2" \
  "GRUB boot loader"

# install GRUB
arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB

# generate a GRUB configuration file
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg

### FINALIZE ###

# installation complete
gum style --align center --foreground 99 --width 60 --margin "1 2" --padding "1 2" \
  "Installation complete. If there were no error messages, please reboot and login \
as root or as $username."
