#!/usr/bin/sh

if [ ! -d /etc/pacman.d/hooks ]; then
  /usr/bin/mkdir -p /etc/pacman.d/hooks
  echo "created directory 'etc/pacman.d/hook'" fi

addhook_orphans() {
  # check for orphans after installing, upgrading, or removing a package
  tee /etc/pacman.d/hooks/orphans.hook >/dev/null <<EOF
[Trigger]
Operation = Remove
Type = Package
Target = *

[Action]
Description = Searching for orphaned packages...
When = PostTransaction
Exec = /usr/bin/sh -c '/usr/bin/pacman -Qtdq || /usr/bin/printf ""'
EOF
}

addhook_newuser() {
  # remove zsh newuser script if it exists
  tee /etc/pacman.d/hooks/zsh-newuser.hook >/dev/null <<EOF
[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = zsh

[Action]
Description = Removing zsh newuser script...
When = PostTransaction
Exec = /usr/bin/rm -f /usr/share/zsh/scripts/newuser
EOF
}

addhook_esc2caps() {
  # map the <ESC> to the physical Caps Lock key and disable the Esc key
  tee /etc/pacman.d/hooks/esc2caps.hook >/dev/null <<EOF
[Trigger]
Operation = Install
Operation = Upgrade
Type = File
Target = /usr/share/X11/xkb/keycodes/evdev

[Action]
Description = Unsetting Esc and mapping its function to the Caps Lock key...
When = PostTransaction
Exec = /usr/share/libalpm/scripts/esc2caps
EOF
}

addscript_esc2caps() {
  # script to do the key mapping
  tee /usr/share/libalpm/scripts/esc2caps >/dev/null <<EOT
#!/bin/sh

evdev='/usr/share/X11/xkb/keycodes/evdev'
mapped=\$(/usr/bin/grep -o '<ESC> = 66;' \$evdev)

if  [ -z "\$mapped" ]; then
  sed -i 's/<CAPS> = 66/\/\/ <CAPS> = 66/' \$evdev # unset the <CAPS> keymap
  sed -i 's/<ESC> = 9/<ESC> = 66/' \$evdev # map <ESC> to Caps Lock (keycode 66)
  sed -i 's/<HENK> = 100/<HENK> = 9/' \$evdev # map <HENK> the Esc (keycode 9)
fi

unset evdev mapped
EOT
}

addhook_orphans && echo "[hook] created orphans.hook" ||
  echo "[hook] failed to create orphans.hook"

addhook_newuser && echo "[hook] created zsh-newuser.hook" ||
  echo "[hook] failed to create zsh-newuser.hook"

addhook_esc2caps && echo "[hook] created esc2caps.hook" ||
  echo "[hook] failed to create esc2caps.hook"

if addscript_esc2caps; then
  echo "[script] created esc2caps"
  # change permission to -rwxr-xr-x
  chmod 755 /usr/share/libalpm/scripts/esc2caps || echo "[script] failed set permissions"
else
  echo "[script] esc2caps failed!"
fi
